### ISSUE TITLE
Is it possible to group files when uploading?

### ISSUE THREAD

**Issue by joelmzj** [iw4p/telegram-cloud#29]
Hi. I have a questions. Is it possible to group files when uploading?

I mean something like this:
<a href="https://ibb.co/0F8vL7h"><img src="https://i.ibb.co/7R8LDf2/Captura-de-pantalla-2021-07-25-13-26-26.png" alt="Captura-de-pantalla-2021-07-25-13-26-26" border="0"></a>

<a href="https://imgbb.com/"><img src="https://i.ibb.co/2sYhdKD/Captura-de-pantalla-2021-07-25-13-30-09.png" alt="Captura-de-pantalla-2021-07-25-13-30-09" border="0"></a>

 Maybe it isn't because of at this time is not possible to upload several files at the same time using your tool.
 
 Whatever. I have another question. Is it possible to upload several files, not at the same time, but one by one as a queue and then group them? (Lol) It will be very great to have an option like this.
 
 Thanks in advance for your work and your help.

**Comment by iw4p** [comment]
Hello,
It's possible to group items before sending but I checked Telethon and they don't have this option.
So we've to wait until they add this feature.

And for the second question, You have to make your queue system based on your needs, because adding a queue downloader/uploader does not seem right and efficient.

Your welcom.
